version: 2.1

jobs:
  build-dotnet:
    resource_class: small
    docker:
      - image: hughperkins/unity-ci:latest
    steps:
      - checkout
      - run:
          name: Run
          command: |
            bash ci/build-ci.sh
      - store_artifacts:
          path: PeacefulPie/bin/Debug/netstandard2.1/PeacefulPie.dll
      - store_artifacts:
          path: PeacefulPie/bin/Debug/netstandard2.1/PeacefulPie.deps.json
      - store_artifacts:
          path: PeacefulPie/bin/Debug/netstandard2.1/PeacefulPie.pdb

  deploy-python:
    resource_class: small
    docker:
      - image: cimg/python:3.10.9
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Run
          command: |
            bash ci/deploy-python.sh

# 'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python -'
# 'curl -sSL https://install.python-poetry.org | python3 -'
# 'poetry self add "poetry-dynamic-versioning[plugin]"'

workflows:
  build:
    jobs:
      - build-dotnet:
          filters:
            tags:
              only: /.*/
      - deploy-python:
          filters:
            # branches:
            #   ignore: /.*/
            tags:
              only: /^v.*/
