version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: hughperkins/unity-ci:latest
    steps:
      - checkout
      - run:
          name: Run
          command: |
            bash ci/build-ci.sh
      - store_artifacts:
          path: PeacefulPie/bin/Debug/netstandard2.1

workflows:
  main:
    jobs:
      - build
